void	*ft_calloc(int a, int b);
char	*ft_fill(char *str, char delim, char *token);
char	*ft_trim(char *str, char delim);
char	*ft_strtrim(char *str, char delim);
char	**ft_split(char *str, char delim, int length);
char	*ft_join(char **av);
int	*ft_atoi(char **output, int length);
int	*ft_get_list(char *str);
int	ft_token(char *str, char delim, char **output, int length);
int	ft_delim(char *str, char delim);
int	ft_free_v2(char **str, int a);
int	ft_strlen(char *str);
int ft_av_length(char **av);